# namespaces.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: dns-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: dns-b
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
