# dns-a/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bind-hpa
  namespace: dns-a
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: bind
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20 # Para testar, você pode ajustar esse valor conforme necessário
