# dns-b/service-dns.yaml
apiVersion: v1
kind: Service
metadata:
  name: dns
  namespace: dns-b
spec:
  type: NodePort
  selector:
    app: bind
  ports:
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
      nodePort: 30054
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
      nodePort: 30054 